exclusions = []

additions = [
    # Crates that the compiler recommends
    # rg 'https://crates.io/crates/[a-z_-]+' --glob '*.stderr' --only-matching --no-line-number --no-filename | sort | uniq | cut -d '/' -f 5
    "async-trait",
    "async-recursion",
    "criterion",
    "pprof",
    "bytemuck",
    "itertools",
    "rayon",
    "regex",
    "parse",
    "memchr",
    "arrayvec",
    "smallvec",
    "rustc",
    "bitvec",
    "dashmap",
    "btoi",
    "nom",
    "ascii",
]